<a href="https://colab.research.google.com/github/subin100/DataVisualization/blob/main/Quiz3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Subin Manandhar
###Data Visualization
###Instructor : Dr Nicholas Jacob

In [1]:
from google.colab import auth
auth.authenticate_user()
print('Authenticated')

Authenticated

In [5]:
%%bigquery --project datavisualization-338803
SELECT 
  COUNT(*) as total_rows
FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips`

   total_rows
0     1424786

In [6]:
%%bigquery --project datavisualization-338803
SELECT 
  AVG(duration_minutes)
FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips`

         f0_
0  30.870428

In [8]:
%%bigquery --project datavisualization-338803
SELECT AVG(table.duration_minutes) as average_duration_minutes
FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips` as table

   average_duration_minutes
0                 30.870428

In [9]:
%%bigquery --project datavisualization-338803
SELECT *
FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips`
LIMIT 5

      trip_id  ... duration_minutes
0  9900289692  ...               39
1  9900285987  ...               31
2  9900285989  ...               31
3  9900285991  ...               30
4  9900286140  ...               19

[5 rows x 9 columns]